sudo: required
services:
  - docker
env:
  - TYPO3_VERSION=8.7
  - TYPO3_VERSION=9.5
  - TYPO3_VERSION=10.1
  - TYPO3_VERSION=10.2

script:
  - cd $TYPO3_VERSION
  - docker-compose build
  - docker-compose up -d
  - sleep 10
  - curl -vf http://localhost/typo3/install.php || curl -v http://localhost/typo3/install/
